# Compatibility shim for older Hugo versions that do not auto-discover hugo.toml.
# Keep this file in sync with site/hugo.toml.
baseURL = "https://authprobe.com/"
languageCode = "en-us"
title = "AuthProbe"
copyright = "AuthProbe Authors"
enableRobotsTXT = true
enableEmoji = true
theme = "hugo-bootstrap-theme"
themesdir = "node_modules/@filipecarneiro"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[outputFormats.RSS]
  baseName = "index"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  images = ["/img/logo.svg"]
  author = "AuthProbe"
  description = "authprobe pinpoints MCP OAuth failures. Scan any MCP endpoint and get deterministic findings mapped to RFCs."
  github = "https://github.com/authprobe/authprobe"
  logo = "/img/logo.svg"
  mainMenuLogo = "/img/logo.svg"

  [params.options]
    bootStrapJs = true
    breadCrumb = true

[markup]
  [markup.highlight]
    noClasses = false
    guessSyntax = true
    lineNos = false

[[menu.main]]
  name = "Docs"
  url = "/docs/"
  weight = 10

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/authprobe/authprobe"
  weight = 20

[[menu.social]]
  name = "GitHub"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather'><use href='/images/feather/feather-sprite.svg#github'/></svg>"
  url = "https://github.com/authprobe/authprobe"
  weight = 10

[[menu.social]]
  name = "Discord"
  pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather'><use href='/images/feather/feather-sprite.svg#message-circle'/></svg>"
  url = "https://discord.gg/ZYRjaZEsNV"
  weight = 20
